import { defineField, defineType } from "sanity";

export const widgetType = defineType({
  name: "widget",
  title: "Widgets",
  type: "document",
  fields: [
    defineField({
      name: "area",
      title: "Widget Area",
      type: "string",
      options: {
        list: [
          { title: "Before Header", value: "before-header" },
          { title: "Header Right", value: "header-right" },
          { title: "After Header", value: "after-header" },
          { title: "Before Content", value: "before-content" },
          { title: "After Content", value: "after-content" },
          { title: "Primary Sidebar", value: "primary-sidebar" },
          { title: "Secondary Sidebar", value: "secondary-sidebar" },
          { title: "Footer 1", value: "footer-1" },
          { title: "Footer 2", value: "footer-2" },
          { title: "Footer 3", value: "footer-3" },
          { title: "Footer 4", value: "footer-4" },
          { title: "Top Bar Left", value: "top-bar-left" },
          { title: "Top Bar Right", value: "top-bar-right" },
          { title: "Header Left", value: "header-left" },
          { title: "Blog Sidebar", value: "blog-sidebar" },
          { title: "Page Sidebar", value: "page-sidebar" },
          { title: "Shop Sidebar", value: "shop-sidebar" },
          { title: "After Footer", value: "after-footer" },
          { title: "Off Canvas", value: "off-canvas" },
          { title: "Mobile Menu", value: "mobile-menu" },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "type",
      title: "Widget Type",
      type: "string",
      options: {
        list: [
          { title: "Text", value: "text" },
          { title: "HTML", value: "html" },
          { title: "Menu", value: "menu" },
          { title: "CTA", value: "cta" },
          { title: "Recent Posts", value: "recent-posts" },
          { title: "Newsletter", value: "newsletter" },
          { title: "Social Links", value: "social-links" },
          { title: "Advertisement", value: "advertisement" },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: "title", title: "Title", type: "string" }),
    defineField({ name: "content", title: "Content", type: "text" }),
    defineField({ name: "menuName", title: "Menu Name", type: "string" }),
    defineField({ name: "buttonLabel", title: "Button Label", type: "string" }),
    defineField({ name: "buttonUrl", title: "Button URL", type: "string" }),
    defineField({ name: "order", title: "Order", type: "number", initialValue: 10 }),
    defineField({ name: "count", title: "Number of Posts", type: "number", initialValue: 5, hidden: ({ parent }) => parent?.type !== "recent-posts" }),
    defineField({ name: "imageUrl", title: "Image URL", type: "url", hidden: ({ parent }) => parent?.type !== "advertisement" }),
    defineField({ name: "linkUrl", title: "Link URL", type: "url", hidden: ({ parent }) => parent?.type !== "advertisement" }),
    defineField({ name: "altText", title: "Alt Text", type: "string", hidden: ({ parent }) => parent?.type !== "advertisement" }),
  ],
});
